services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fullstack_app
      MYSQL_DATABASE: fullstack_app
      MYSQL_USER: fullstack_app
      MYSQL_PASSWORD: fullstack_app
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  fullstack_project:
    build: . 
    container_name: fullstack_project
    environment:
      - PORT=:80
      - BASE_URL=http://localhost:8080
      - COOKIE_SECRET=
      - DATABASE=mysql
      - DATABASE_NAME=fullstack_app
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=fullstack_app
      - DATABASE_PASSWORD=fullstack_app
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_HOST=
      - SMTP_PORT=
      - SMTP_SENDER=
      - STRICT_TRANSPORT_SECURITY=false
      - REQUESTS_PER_MINUTE=5
      - CACHE_PARAMETER=
      - CACHE_MAX_AGE=
    depends_on:
      - db
    ports:
      - "8080:80"

volumes:
  db_data: {}
